<?
//Do not edit this file.  Instead, set these variables in config.local.php, which will automatically be included if it exists.

$config['Site title'] = "Map";
$config['Site keywords'] = "map,interactive";
$config['Site description'] = "Interactive Map";
$config['default lat'] = 50.9355;
$config['default long'] = -1.39595;
$config['default zoom'] = 17;
$config['default map'] = "'Map2'";
$config['datasource'] = 'sqldemo';
$config['enabled'] = array('search', 'geobutton', 'toggleicons');
$config['categories']['Transportation'] = 'Transport';
$config['categories']['Restaurants-and-Hotels'] = 'Catering and Accommodation';
$config['categories']['Offices'] = 'Services';
$config['categories']['Culture-and-Entertainment'] = 'Culture and Entertainment';
$config['categories']['Health'] = 'Health and Beauty';
$config['categories']['Tourism'] = 'Tourism and Religion';
$config['categories']['Stores'] = 'Retail';
$config['categories']['Education'] = 'Education';
$config['categories']['Sports'] = 'Sports';

error_reporting(0);
if(file_exists('config.local.php'))
{
	include 'config.local.php';
}

$path = '.';
if(preg_match('/^[a-zA-Z0-9_-]+$/', $_GET['v']))
{
	$version = $_GET['v'];
	$versionparts = explode('_', $version);
	$version = $versionparts[0];
	$path = $version;
	if(file_exists('config.'.$version.'.php'))
	{
		include 'config.'.$version.'.php';
	}
}

if(!is_array($config['datasource']))
{
	$config['datasource'] = array($config['datasource']);
}

function has($id) {
	global $config;
	return in_array($id, $config['enabled']);
}

function show($id) {
	global $config;
	if(!in_array($id, $config['enabled']))
	{
		echo "style='display:none'";
	}
}

class DataSource{
	static function getAll(){}
	static function getEntries($q, $cats){}
	static function getDataSets(){}
	static function getDataSetExtras(){}
	static function getAllSites(){}
	static function getAllBuildings(){}
	static function processURI($uri){return false;}
	
	static $iconpath = 'http://opendatamap.ecs.soton.ac.uk/img/icon/';
	
	static function convertIcon($icon)
	{	
		global $iconmap;
		if($iconmap == null) include_once "inc/categories.php";
		if(!is_null($iconmap[$icon]))
			return $iconmap[$icon];
		//$icon = str_replace('http://google-maps-icons.googlecode.com/files/', self::$iconpath, $icon);
		//$icon = str_replace('http://data.southampton.ac.uk/map-icons/lattes.png', self::$iconpath.'Restaurants-and-Hotels/coffee.png', $icon);
		return $icon;
	}
}

foreach($config['datasource'] as $ds)
{
	include_once 'ds/'.$ds.'.php';
}

?>
