<?
//Do not edit this file.  Instead, set these variables in config.local.php, which will automatically be included if it exists.

$config['Site title'] = "Map";
$config['Site keywords'] = "map,interactive";
$config['Site description'] = "Interactive Map";
$config['default lat'] = 50.9355;
$config['default long'] = -1.39595;
$config['default zoom'] = 17;
$config['datasource'] = 'sqldemo';

error_reporting(0);
if(file_exists('config.local.php'))
{
	include 'config.local.php';
}

if(preg_match('/^[a-zA-Z0-9]+$/', $_GET['v']))
{
	$version = $_GET['v'];
	if(file_exists('config.'.$version.'.php'))
	{
		include 'config.'.$version.'.php';
	}
}

if(!is_array($config['datasource']))
{
	$config['datasource'] = array($config['datasource']);
}

class DataSource{
	static function getAll(){}
	static function getEntries($q, $cats){}
	static function getDataSets(){}
	static function getDataSetExtras(){}
	static function getAllSites(){}
	static function getAllBuildings(){}
	static function processURI($uri){return false;}
}

foreach($config['datasource'] as $ds)
{
	include_once 'ds/'.$ds.'.php';
}

?>
